# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:20
from __future__ import unicode_literals
import csv
from django.db import migrations


# def add_user(apps, schema_editor):
#     Rater = apps.get_model("movieratings", "Rater")
#     with open('/users/hrumba/week4/day2/django_movies/u.user', encoding="latin-1") as f:
#         reader = csv.reader(f, delimiter='\t')
#         for i in reader:
#             rater = Rater(user_id=i[0], age=i[1], gender=i[2], occupation=i[3], zip_code=i[4])
#             rater.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0002_auto_20161116_2213'),
    ]

    operations = [
        #migrations.RunPython(add_user)
    ]
