# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 22:24
from __future__ import unicode_literals
import csv
from django.db import migrations, models



def add_rater(apps, schema_editor):
    with open("/users/hrumba/week4/day2/django_movies/u.user", "r") as f:
        r = csv.DictReader(f, fieldnames= ['user_id', 'age', 'gender', 'occupation', 'zip_code'],
        delimiter='|')
        Rater = apps.get_model("movieratings", "Rater")
        for row in r:
            m = Rater(**row)
            m.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_auto_20161116_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rater',
            name='gender',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='rater',
            name='occupation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='rater',
            name='zip_code',
            field=models.CharField(max_length=200),
        ),
        migrations.RunPython(add_rater)
    ]
