# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0003_auto_20161118_2003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.TextField(blank=True, max_length=500)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('email', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieratings.Rater')),
            ],
        ),
    ]
