# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:27
from __future__ import unicode_literals
from django.db import migrations
from ..models import Movie, Rater, Rating

#
# def add_profile(apps, schema_editor):
#     raters = models.Rater.objects.all()
#     for i in raters:
#         profile = Profile(login=("R"+i[1]), password=("pass" + i[2]), email=(i[3] + "@gmail.com"), user_id=i[4])
#         profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0004_profile'),
    ]

    operations = [
        
    ]
