# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieratings', '0005_auto_20161119_2227'),
        ('movieratings', '0006_auto_20161119_2235'),
    ]

    operations = [
    ]
